name: CI - Camera & Face Tests

on:
  push:
    branches: [ training-workflow, main ]
  workflow_dispatch:

jobs:
  cam-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (OpenCV)
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python-headless numpy

      - name: Run camera FPS test (no real webcam needed)
        run: |
          python tests/run_cam_test.py --seconds 5 --width 640 --height 480 --log cam.log

      - name: Upload cam.log
        uses: actions/upload-artifact@v4
        with:
          name: cam-log
          path: cam.log

  face-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: System packages for dlib (safe even if wheels exist)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libopenblas-dev liblapack-dev

      - name: Install Python deps (dlib / face_recognition)
        run: |
          python -m pip install --upgrade pip
          pip install "dlib==20.0.0" "face_recognition==1.3.0" pillow numpy

      - name: Run dlib face-ID test (5 photos > 80%)
        run: |
          python tests/run_face_test.py --log id_test.log

      - name: Upload id_test.log
        uses: actions/upload-artifact@v4
        with:
          name: id-test-log
          path: id_test.log
