name: CI - Camera & Face Tests

on:
  push:
    branches: [training-workflow, main]
  workflow_dispatch:

jobs:
  cam-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          pwd
          ls -lah
          echo "---- tests ----"
          ls -lah tests || true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (OpenCV)
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python-headless numpy

      - name: Run camera FPS test (no real webcam needed)
        run: python tests/run_cam_test.py --seconds 5 --width 640 --height 480 --log cam.log

      - uses: actions/upload-artifact@v4
        with:
          name: cam-log
          path: cam.log

  face-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          pwd
          echo "---- root ----"
          ls -lah
          echo "---- tests ----"
          ls -lah tests || true
          echo "---- personA ----"
          ls -lah tests/assets/personA || true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: System packages for dlib
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libopenblas-dev liblapack-dev

      - name: Install Python deps (dlib / face_recognition)
        run: |
          python -m pip install --upgrade pip
          pip install "dlib==20.0.0" "face_recognition==1.3.0" pillow numpy

      - name: Run dlib face-ID test (your photos if present; else fallback)
        run: |
          if [ -d tests/assets/personA ] && ls tests/assets/personA/* >/dev/null 2>&1; then
            echo "Using your photos from tests/assets/personA"
            mkdir -p tests/_artifacts/debug
            python tests/run_face_test.py \
              --input-dir tests/assets/personA \
              --log id_test.log \
              --threshold 0.6 \
              --target_pass_ratio 0.8 \
              --save-dir tests/_artifacts/debug
          else
            echo "No personal photos found, running built-in sample variants"
            mkdir -p tests/_artifacts/variants
            python tests/run_face_test.py \
              --log id_test.log \
              --save-dir tests/_artifacts/variants
          fi

      - name: Upload id_test.log
        uses: actions/upload-artifact@v4
        with:
          name: id-test-log
          path: id_test.log

      - name: Upload id_test_files.txt (filenames & matches)
        uses: actions/upload-artifact@v4
        with:
          name: id-test-files
          path: id_test_files.txt
          if-no-files-found: ignore

      - name: Upload debug/variants (if any)
        uses: actions/upload-artifact@v4
        with:
          name: face-debug-or-variants
          path: |
            tests/_artifacts/debug/*.jpg
            tests/_artifacts/variants/*.jpg
          if-no-files-found: ignore
